# Generated by Django 6.1 on 2026-08-23 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACTIVIDAD', 'Actividad'), ('ENTREGA', 'Entrega'), ('CORRECCION', 'Corrección'), ('VENCIMIENTO', 'Vencimiento'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('clave', models.CharField(blank=True, max_length=200, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('clave__isnull', False)), fields=('usuario', 'clave'), name='notificacion_clave_unica_por_usuario')],
            },
        ),
    ]
