# Generated by Django 6.1 on 2026-08-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='autoridad_cargo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Cargo de la autoridad'),
        ),
        migrations.AddField(
            model_name='institucion',
            name='autoridad_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de la autoridad'),
        ),
    ]
