# Generated by Django 6.1 on 2026-08-20 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INSCRIPTO', 'Inscripto'), ('CURSANDO', 'Cursando'), ('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado'), ('ABANDONO', 'Abandonó')], default='INSCRIPTO', max_length=20)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.curso')),
            ],
            options={
                'ordering': ['alumno__last_name', 'alumno__first_name'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'alumno'), name='inscripcion_unica_por_curso_alumno')],
            },
        ),
    ]
