# Generated by Django 6.1 on 2026-08-18 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('instituciones', '0001_initial'),
        ('usuarios', '0002_usuario_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembresiaInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='instituciones.institucion')),
                ('roles', models.ManyToManyField(blank=True, related_name='membresias_institucionales', to='auth.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'membresía institucional',
                'verbose_name_plural': 'membresías institucionales',
                'ordering': ['institucion__nombre', 'usuario__last_name', 'usuario__first_name'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'institucion'), name='membresia_unica_usuario_institucion')],
            },
        ),
    ]
