# Generated by Django 6.1 on 2026-08-22 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_clase'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TEXTO', 'Texto'), ('ARCHIVO', 'Archivo'), ('ENLACE', 'Enlace'), ('VIDEO', 'Video'), ('EMBEBIDO', 'Embebido')], max_length=20)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('texto', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='contenidos/')),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contenidos', to='contenidos.clase')),
            ],
            options={
                'verbose_name': 'contenido de clase',
                'verbose_name_plural': 'contenidos de clase',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('clase', 'orden'), name='orden_contenido_unico_por_clase')],
            },
        ),
    ]
