# Generated by Django 6.1 on 2026-08-23 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0003_contenidoclase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=True)),
                ('fecha_completada', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_clases', to=settings.AUTH_USER_MODEL)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_alumnos', to='contenidos.clase')),
            ],
            options={
                'verbose_name': 'progreso de clase',
                'verbose_name_plural': 'progresos de clases',
                'constraints': [models.UniqueConstraint(fields=('alumno', 'clase'), name='progreso_clase_unico_por_alumno')],
            },
        ),
    ]
