# Generated by Django 6.1 on 2026-08-23 00:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenidos', '0003_contenidoclase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('consigna', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='actividades/adjuntos/')),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, default=10, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('permite_texto', models.BooleanField(default=True)),
                ('permite_archivo', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='contenidos.clase')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['fecha_limite', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actividades/entregas/')),
                ('estado', models.CharField(choices=[('ENTREGADA', 'Entregada'), ('CORREGIDA', 'Corregida')], default='ENTREGADA', max_length=20)),
                ('fecha_entrega', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('devolucion', models.TextField(blank=True)),
                ('fecha_correccion', models.DateTimeField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='actividades.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_actividades', to=settings.AUTH_USER_MODEL)),
                ('corregido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_corregidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-fecha_entrega'],
                'constraints': [models.UniqueConstraint(fields=('actividad', 'alumno'), name='entrega_unica_por_actividad_alumno')],
            },
        ),
    ]
