# Generated by Django 6.1 on 2026-08-24 01:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('ENTREGADA', 'Entregada'), ('CORREGIDA', 'Corregida'), ('REHACER', 'Requiere nueva entrega')], default='ENTREGADA', max_length=20),
        ),
        migrations.CreateModel(
            name='IntentoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('texto', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='actividades/intentos/')),
                ('estado', models.CharField(choices=[('ENTREGADO', 'Entregado'), ('REHACER', 'Rehacer'), ('CORREGIDO', 'Corregido')], default='ENTREGADO', max_length=20)),
                ('fecha_entrega', models.DateTimeField()),
                ('calificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('devolucion', models.TextField(blank=True)),
                ('fecha_correccion', models.DateTimeField(blank=True, null=True)),
                ('corregido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intentos_corregidos', to=settings.AUTH_USER_MODEL)),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='actividades.entrega')),
            ],
            options={
                'ordering': ['numero'],
                'constraints': [models.UniqueConstraint(fields=('entrega', 'numero'), name='intento_unico_por_entrega_numero')],
            },
        ),
    ]
