# Generated by Django 6.1 on 2026-08-25 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_alter_entrega_estado_intentoentrega'),
        ('contenidos', '0004_progresoclase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_apertura', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('intentos_permitidos', models.PositiveIntegerField(default=1)),
                ('visible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuestionarios', to='contenidos.clase')),
            ],
            options={
                'verbose_name': 'cuestionario',
                'verbose_name_plural': 'cuestionarios',
                'ordering': ['fecha_limite', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IntentoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intentos_cuestionarios', to=settings.AUTH_USER_MODEL)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='actividades.cuestionario')),
            ],
            options={
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='PreguntaCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('puntaje', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('orden', models.PositiveIntegerField(default=1)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='actividades.cuestionario')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcionCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='actividades.preguntacuestionario')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='actividades.intentocuestionario')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='actividades.opcioncuestionario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='actividades.preguntacuestionario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='intentocuestionario',
            constraint=models.UniqueConstraint(fields=('cuestionario', 'alumno', 'numero'), name='intento_cuestionario_unico'),
        ),
        migrations.AddConstraint(
            model_name='respuestacuestionario',
            constraint=models.UniqueConstraint(fields=('intento', 'pregunta'), name='respuesta_unica_por_pregunta_intento'),
        ),
    ]
