# Generated by Django 6.1 on 2026-08-25 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_avisocurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=40, unique=True)),
                ('estado', models.CharField(choices=[('VALIDO', 'Válido'), ('ANULADO', 'Anulado')], default='VALIDO', max_length=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificados', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['-fecha_emision'],
                'constraints': [models.UniqueConstraint(fields=('curso', 'alumno'), name='certificado_unico_curso_alumno')],
            },
        ),
    ]
