# Generated by Django 6.1 on 2026-08-25 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_certificado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_curso', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'conversación del curso',
                'verbose_name_plural': 'conversaciones del curso',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mensajes_curso_enviados', to=settings.AUTH_USER_MODEL)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='cursos.conversacioncurso')),
            ],
            options={
                'verbose_name': 'mensaje del curso',
                'verbose_name_plural': 'mensajes del curso',
                'ordering': ['fecha_creacion', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='conversacioncurso',
            constraint=models.UniqueConstraint(fields=('curso', 'alumno'), name='conversacion_unica_curso_alumno'),
        ),
    ]
