# Generated by Django 6.1 on 2026-08-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_conversacioncurso_mensajecurso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecurso',
            name='leido_por_alumno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mensajecurso',
            name='leido_por_equipo',
            field=models.BooleanField(default=False),
        ),
    ]
